### ISSUE TITLE
Button flicker on setup screen

### ISSUE THREAD

**Issue by StevenDixonDev** [SeanMcP/sushi-go-friend#1]
Setup button flickers when hovering on bottom edge of button. Looks like an issue with the button becoming smaller after hover.

**Comment by SeanMcP** [comment]
## Description
On Desktop, hovering near the bottom of the "Setup" button on `/` flickers.

## Expected behavior
There is no change in size on button `:hover`

## Actual behavior
The yellow hover state is smaller, resulting in a flickering effect.

## Environment
**Confirmed**:
- OS: Windows
- Browser: Chrome

**Comment by SeanMcP** [comment]
@StevenDixonDev Would you like to take a look and make a PR to fix this?
